### ISSUE TITLE
Generic MojoDatabase ORM?

### ISSUE THREAD

**Issue by Bhushan30** [cpjolicoeur/mojo-database#5]
Hi..
How this ORM makes generic. As per my understanding this MojoDatabase ORM map directly to a table in SQLiteDB. But in future suppose i want to changed my database so its not feasible solution.
So is it possible to separate out sql part and ORM part. How it can be make generic so that other database also support. If this ORM is generic then it will be useful more. So kindly please provide your valuable suggestion.

**Comment by cpjolicoeur** [comment]
If you want to add support for a database type other than sqlite, please submit a pull request with a patch.
